# Generated by Django 2.2.8 on 2020-06-29 23:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('troubleticket', '0005_stagetroubleticketanomaly_tt_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='TroubleTicketGroupFollowUpAnomaly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_up_datetime', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=1000)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_by_group', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_to_group', to=settings.AUTH_USER_MODEL)),
                ('trouble_ticket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='troubleticket.TroubleTicketGroupAnomaly')),
            ],
        ),
    ]
